api:
  id: "18273082"
# process API authentication details
client:
  id: ''
  secret: ''
https:
  private:
    port: "8092" 
retry:
 count: '2'
 interval: '20000'
to:
  Address: "lchalla.cw@huronconsultinggroup.com,lchalla.cw@hcg.com,t-9chall@uchicago.edu"

project:
  host: "itsapi-dev.uchicago.edu/system/oracle/v1/api"
  path: "/project"
awardsbudget:
  host: "itsapi-dev.uchicago.edu/system/oracle/v1/api"
  path: "/awardsBudget"
awards:
  host: "itsapi-dev.uchicago.edu/system/oracle/v1/api"
  path: "/awards"
purchaseRequisitions:
  host: "itsapi-dev.uchicago.edu"
  basePath: "system/oracle/v1/api"
  path: "/purchaseRequisitions"
expenses:
  host: "itsapi-dev.uchicago.edu"
  basePath: "system/oracle/v1/api"
  path: "/expenses"
  timeout: "90000"
invoices:
  host: "itsapi-dev.uchicago.edu"
  basePath: "system/oracle/v1/api"
  path: "/invoices"